### ISSUE TITLE
Этап 2. Ревью

### ISSUE THREAD

**Issue by sOlnblshkO** [2Jinx/YouTube.NET#14]

**Comment by sOlnblshkO** [comment]
1) Обоснуйте решение разделить фронт на два отдельных проекта.
2) Вы выбрали .net8 в качестве фреймворка для бэка, но всё равно завели class Program внутри которого есть метод Main? А зачем? Если не обосновано, то надо привести к low code
3) namespace Users_account_management - это кошмар. Придерживайтесь, пожалуйста, установленного code style. В данном случае должно было быть namespace UsersAccountManagement
4)  Если уж вы всё таки сможете обосновать своё решение того, почему фронт разделен на два проекта, то эти папки (accounts, youtube) надо объеденить в один "front"
5) Папку с бэком надо переименовать на UserAccoutManagment и соответственно все namespace внутри файлов .cs и .csproj
6) Бэк нужно закинуть в отдельную папку "Backend" и там же стоит разделить БД в отдельный подпроект UserAccountManagment.Database. Сюда же перенести папку DomainModels 
7) Почему контроллеры в Infrastructure, а не в папке Controllers?
8) 
![image](https://github.com/2Jinx/YouTube.NET/assets/22156715/e0c35f3c-3356-469a-9312-410eafea9f29)
В названии файлов избегайте использование "пробелов". Иногда это может привести к проблемам при сборках на разных системах. Про папки тоже самое
9) Dto файлы стоит раскидать на разные папки - чтобы не копился мусор. Затем в названия DTO можно сделать приписку Response или Request чтобы было понятнее какая цель у DTO
10) Использование маппера некорретно: маппер навешивается между сущностью и дто, а вы написали "MapperProfile". Это дает ощущение, что все мапинги буду лежать там - что не есть хорошо. Стоит писать UserProfile, <SomeEntity>Profile и так далее
11) Во всём коде не хватает форматирование кода. В райдере по умолчанию "Ctrl + Alt + L". В VS по умолчанию "Ctrl+K, Ctrl+D"
12) В C# принято private поля писать через _<название поля>. В вашем случае должно быть
`private readonly IDatabase _redisCache; `
13) А почему БД в InMemory?
14) Почему стандартными appsettings.json не пользуетесь?

**Comment by 2Jinx** [comment]
1) Решение разделить фронт на два отдельных проекта связана с тем, что в основном мы пытаемся повторить оригинальный сервис, также это помогает разделить ответственности. В оригинале у гугла свой сервис по работе с аккаунтами и сервис YouTube. Ну и в дальнейшем будет проще расширить функционал сервиса по управлению аккаунтами (смена имени, никнейма, сброс пароля, добавление аватарки и т.д.). Также такую структуру будет куда легче поддерживать, так как со временем проект разрастается. В дальнейшем будет лучше и сам монолит ютуба разделить на микрофронт.
2) Замечание учтем, приведем к low code
3) Данное недоразумение будет исправлено
4) Объединение проектов в папку `front` предполагалось, только в этом этапе у нас сдача только бэка авторизации, поэтому просто не успел все выкинуть в отдельную папку, сам проект с аккаунтами был добавлен для будующего склеивания с бэком и реализацией авторизации / регистрации.
5) Исправим
6) Мы планируем выстраивать чистую архитектуру на 3 этапе, данный проект - временное решение, код из которого будет использован далее. Проект создан чтобы закрыть требования к этапу 2.
7) Контролеры входят в слой Infrastructure, который будет вынесен отдельно в чистой архитектуре.
8) Будет исправлено
9) Хорошо, опять же все это будет сделано в чистой архитектуре, данный проект использовался как временный для защиты этапа 2.
10) MapperProfile создан для реализации авторизации и регистрации, в дальнейшем планировалась декомпозиция.
11) Исправим
12) Исправим
13) БД в InMemory использовалась исключительно в качестве временного решения. На тот момент у нас была задача спроектировать базу данных, использовать ее мы пока не планировали. В дальнейшем будем использовать свою базу.
14) Был создан пустой проект, вместо asp-приложения, поэтому json создавался вручную, опять же данный проект лишь временное решение, на следующих этапах будет использован другой


благодарим за ревью, замечания и недочеты исправим
